Added description of XAL to the front page.
expertanalytics/website pull request #121
Opened 2021-05-26 04:01 UTC by kememil

2021-05-27 07:21 UTC, kememil commented
This PR is related to PR #122 where the description of XAL has been updated. The old text from the About us section has been moved to the front page.

2021-05-27 08:20 UTC, skavhaug requested changes

2021-05-27 08:20 UTC, skavhaug commented on content/_index.md
> +that our solutions will meet their needs and beyond.
I do not really like this text. What do we do to improve?

2021-05-27 08:35 UTC, kememil commented on content/_index.md
> +that our solutions will meet their needs and beyond.
I can agree to that. This is the old text from the About us section and we should decide on what to put on the front page and what to leave for the About section. See #122 for the updated text in the About us section.

2021-05-27 08:38 UTC, skavhaug commented on content/_index.md
> +that our solutions will meet their needs and beyond.
Yeah, now that we actually go though this and improve, we should take the opportunity to freshen it up.

2021-05-27 09:09 UTC, kememil commented on content/_index.md
> +that our solutions will meet their needs and beyond.
How about this one from the slide deck for the front page:
On demand Expertise in Scientific & Industrial Data Analytics

2021-05-27 09:27 UTC, skavhaug commented on content/_index.md
> +that our solutions will meet their needs and beyond.
That's a good start. Please feel free to try out some formulations, and I'll do my best to help out :)

2021-06-03 15:16 UTC, eigilhs commented on content/_index.md
> +On Demand Expertise in Scientific & Industrial Data Analytics
I think "on-demand" should be hyphenated when used as an adjective and placed before the noun.
```suggestion
On-Demand Expertise in Scientific & Industrial Data Analytics
```

2021-08-19 09:06 UTC, mandus approved these changes
I'm happy with this - and it's better than what we have, so let's go with it?

2021-08-19 13:36 UTC, skavhaug requested changes

2021-08-19 13:36 UTC, skavhaug commented on content/_index.md
> +that our solutions will meet their needs and beyond.
Let's remove the last sentence, and I'm happy to approve this PR ;)

2021-08-19 13:47 UTC, skavhaug approved these changes

2021-08-19 13:47 UTC, merged