Updated the About us section and rearranged consultants alphabetically
expertanalytics/website pull request #122
Opened 2021-05-26 04:26 UTC by kememil

2021-05-27 08:43 UTC, skavhaug requested changes
Generally, I like this, but there are a couple of things to change. One simple, one more difficult :)

2021-05-27 08:43 UTC, skavhaug commented on content/about/_index.md
> +Expert Analytics has a strong focus on research and development and has a keen interest in the use of computational methods and data science in the industry. The company therefore sees great value an
hydro power plants

2021-05-27 08:52 UTC, kememil commented on content/about/_index.md
> +Expert Analytics has a strong focus on research and development and has a keen interest in the use of computational methods and data science in the industry. The company therefore sees great value an
Ok. I can change that to "wind- and hydropower plants".

2021-05-27 08:53 UTC, kememil commented on content/about/_index.md
> +Our experts have years of hands-on experience in computational science and modern industrial software development. This translates into an ability to analyze and solve complex challenges for the clie
This is basically the same sentence as in the old About Us. And I agree that it is too fluffy. Let me come up with an alternative :)

2021-05-27 09:07 UTC, kememil commented on content/about/_index.md
> +Our experts have years of hands-on experience in computational science and modern industrial software development. This translates into an ability to analyze and solve complex challenges for the clie
Suggestion:
Our experts have years of hands-on experience in computational science and robust industrial software development. We thrive on complex challenges and use scientific methods and technical excellence to develop flexible and tailored solutions that close the gap between needs and tools.

2021-06-02 07:37 UTC, kememil commented on content/about/_index.md
> +Our experts have years of hands-on experience in computational science and modern industrial software development. This translates into an ability to analyze and solve complex challenges for the clie
@skavhaug Is this good for now? I think at least it is better than what is online right now, and then we can always refine :)

2021-08-19 09:00 UTC, mandus approved these changes
looks fine to me; about time to roll this out?

2023-09-03 17:36 UTC, grytveten commented
@mandus, kan vi lukke denne eller er det fortsatt snakk om å merge?

2023-09-08 07:01 UTC, mandus commented
> @mandus, kan vi lukke denne eller er det fortsatt snakk om å merge?

Det var vel et forsøk på å forbedre teksten - og det behovet er der fortsatt! Så i påvente av at vi får gjort en skikkelig oppgradering av websidene kan man kanskje ta en liten iterasjon på denne PRen og så pushe den ut?

2023-09-08 12:02 UTC, skavhaug commented
I'll change the text to the one suggested by Emil, and then I think we should roll it out :)

2023-09-08 12:03 UTC, skavhaug commented
Haha, 'twas changed already.

2023-09-08 12:04 UTC, skavhaug approved these changes

2023-09-08 12:04 UTC, merged