Christian profile
expertanalytics/website pull request #176
Opened 2023-12-06 11:49 UTC by christian-pedersen

Website profile for Christian

2023-12-07 13:03 UTC, alexanfl requested changes
Looks good! I have added a code suggestion to fix some typos. 

Regarding the content, I only have one suggestion. That is to tie in the technologies you used and the development practices in your various projects. If you have worked on setting up a software pipeline for an experiment or created a software system for the analyses, then that is great to tell potential customers. As many of our clients rely on us to deliver software, they need to know we can deliver. :)

2023-12-12 11:45 UTC, alexanfl approved these changes
lgtm :)

2023-12-12 12:17 UTC, skavhaug approved these changes

2023-12-12 12:27 UTC, skavhaug approved these changes

2023-12-12 12:28 UTC, merged